### ISSUE TITLE
v0.9.2 task list

### ISSUE THREAD

**Issue by tamurayoshiya** [qmu/mcc#1]
### Bug Fix / Refactoring

* [x] fix GitHub OAuth problem
* [x] show no blank line if comments does not exist
* [x] show message if mcc cannot find any config
* [x] rename stacks to widgets

### Feature

* [x] add LICENSE, VERSION
* [x] add --version cmd flag
* [x] add schema_version to mcc.yml and implement compatibility checker
* [x] add README
* [x] add _example dir for config examples
* [x] markdown highlight for note widget
* [ ] add env option in the Menu widget section of config
    * exporting enviromental variables when the command executed
* [ ] support multiline command for the Menu widget in config
* [ ] add text file widget (loading .mkd, .txt, what ever text file just to display like not widget)
* [ ] add git status widget
* [ ] add docker status widget
    * list container names on the config, which you want to check its status
