### ISSUE TITLE
v0.9.3 task list

### ISSUE THREAD

**Issue by tamurayoshiya** [qmu/mcc#2]
### Bug Fix / Refactoring

* [x] modify authenticate process of github(ui render first)
* [x] fix version sub command to show without config path
* [x] let github client init in goroutin not to block cursor movement after rendering widgets
* [x] fix cursor disappear at the bottom of the GitHub Issue widget
* [x] authenticate only if the private repo is configured for github widget
* [x] GitHub Enterprise support on the config yaml

### Feature

* [x] add env option in the Menu widget section of config
    * exporting enviromental variables when the command executed
* [x] support multiline command for the Menu widget in config
* [ ] add text file widget (loading .mkd, .txt, what ever text file just to display like note widget)
* [ ] add git status widget
* [ ] add docker status widget
    * list container names on the config, which you want to check its status
