### ISSUE TITLE
v0.9.4 task list

### ISSUE THREAD

**Issue by tamurayoshiya** [qmu/mcc#3]
### Bug Fix / Refactoring

* [x] Fix unhandle error of termui initialization
* [x] Modify ui init to handle non supported widget type 
* [x] Fix moving cursor on 3 rows layout
* [x] Highlight timestamp on Tail File Widget
* [x] Add tab keybinding to move widgets 
* [x] Modify hard coded "vim" on key press Enter in Git Status Widget

### Feature

* [x] Implement text file widget (loading .mkd, .txt, what ever text file just to display like note widget)
* [x] Implement git status widget
* [ ] Implement Docker Status Widget
    * list container names on the config, which you want to check its status
* [x] Implement Tail File Widget
