### ISSUE TITLE
v0.9.6 task list

### ISSUE THREAD

**Issue by tamurayoshiya** [qmu/mcc#5]
### Bug Fix / Refactoring

* [x] Fix lost focus problem when github issue widget loaded
* [x] Fix git status widget too slow
* [x] Fix tail file widget too slow
* [x] Add view_manger_test.go
* [x] Make initialization faster using groutine
* [x] Implement lazy widget initialization (init when displayed by switching tab)

### Feature

* [ ] Implement color scheme option on config
* [ ] Implement mysql db schema browser 
* [ ] Implement docker tail widget
* [ ] Implement min/max of height/width config for row/col to show/hide like CSS3 media query
* [ ] Implement help tab
* [ ] Implement command prompt on footer
    * [ ] / for search (n for next match)
    * [ ] : for some command
* [ ] Add layout order option (vertical/horizontal) for docker status widget
* [ ] Implement command executer widget (run some command at starting mcc and show the output)
* [ ] Hide tab selector if defined only one tab
